baseURL = 'https://thelandofrah.com/'
languageCode = 'en-us'
title = 'The Land of Rah'

[params]
  cover_dimming_class = "bg-transparent"
  body_classes = "avenir"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]

  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 1

  [[menu.main]]
    name = "Art"
    url = "/art/"
    weight = 2

  [[menu.main]]
    name = "Comics"
    url = "/comics/"
    weight = 3

  [[menu.main]]
    name = "Videos"
    url = "/videos/"
    weight = 4

  [[menu.main]]
    name = "Maps"
    url = "/maps/"
    weight = 5

  [[menu.main]]
    name = "Upcoming Events"
    url = "/upcoming-events/"
    weight = 6

  [[menu.main]]
    name = "Merch"
    url = "/merch/"
    weight = 7

  [[menu.main]]
    name = "Mailing List"
    url = "/mailing-list/"
    weight = 9

  [[menu.main]]
    name = "Past Events / Photos"
    url = "/events/"
    weight = 8

  [[menu.main]]
    name = "Upcoming Events"
    url = "/upcoming-events/"
    weight = 5.5
